layoutdir = "layouts"
builddrafts = false
baseurl = "https://florentviel.com"
canonifyurls = true
googleAnalytics = "UA-32451634-1"
Title = "CV de Florent Viel"
contentdir = "content/fr"
publishdir = "public/fr"

[params]
    author = "Florent Viel"
    copyright = "2016"
    email = "contact@florentviel.com"
    locale = "fr"
